-- Insert sample data with realistic approach - only insert data that doesn't require auth.users
-- Sample marketplace listings 
INSERT INTO public.marketplace (id, seller_id, title, description, category, price, condition, location, status, tags, images, created_at) VALUES
(gen_random_uuid(), (SELECT id FROM profiles LIMIT 1), 'Fender Stratocaster Electric Guitar', 'Excellent condition Fender Stratocaster. Perfect for studio recordings and live performances.', 'instrument', 75000, 'excellent', 'Bangalore, Karnataka', 'available', ARRAY['guitar', 'fender', 'electric'], ARRAY['https://images.unsplash.com/photo-1564186763535-ebb21ef5277f'], now() - interval '5 days'),
(gen_random_uuid(), (SELECT id FROM profiles LIMIT 1), 'Audio-Technica AT2020 Microphone', 'Professional studio condenser microphone. Barely used, comes with original packaging.', 'equipment', 12000, 'good', 'Delhi', 'available', ARRAY['microphone', 'studio', 'audio-technica'], ARRAY['https://images.unsplash.com/photo-1583394838336-acd977736f90'], now() - interval '8 days'),
(gen_random_uuid(), (SELECT id FROM profiles LIMIT 1), 'Tabla Set - Professional Grade', 'Handcrafted tabla set made by renowned tabla maker. Rich, resonant sound quality.', 'instrument', 35000, 'good', 'Mumbai, Maharashtra', 'available', ARRAY['tabla', 'percussion', 'indian-classical'], ARRAY['https://images.unsplash.com/photo-1578662996442-48f60103fc96'], now() - interval '12 days'),
(gen_random_uuid(), (SELECT id FROM profiles LIMIT 1), 'Yamaha P-125 Digital Piano', 'Excellent digital piano for students and professionals. 88 weighted keys, great touch response.', 'instrument', 45000, 'excellent', 'Chennai, Tamil Nadu', 'available', ARRAY['piano', 'yamaha', 'digital'], ARRAY['https://images.unsplash.com/photo-1520523839897-bd0b52f945a0'], now() - interval '20 days');

-- Sample gigs
INSERT INTO public.gigs (id, client_id, title, description, event_type, location, event_date, duration_hours, budget_min, budget_max, required_skills, status, created_at) VALUES
(gen_random_uuid(), (SELECT id FROM profiles LIMIT 1), 'Wedding Reception Performance', 'Looking for a classical vocalist for an intimate wedding reception in Mumbai. Traditional Indian songs preferred.', 'wedding', 'Four Seasons Hotel, Mumbai', '2024-12-15 18:00:00', 3, 15000, 25000, ARRAY['Professional attire', 'Own instruments', 'Classical training'], 'open', now() - interval '7 days'),
(gen_random_uuid(), (SELECT id FROM profiles LIMIT 1), 'Album Recording Session', 'Need session musicians for upcoming album. Guitar, bass, and drums required.', 'recording', 'Sonic Wave Studios, Delhi', '2024-12-20 10:00:00', 8, 30000, 45000, ARRAY['Studio experience', 'Own instruments', 'Flexibility with timing'], 'open', now() - interval '5 days'),
(gen_random_uuid(), (SELECT id FROM profiles LIMIT 1), 'Corporate Event Entertainment', 'Annual company celebration needs live music performance. Mix of popular and classical songs.', 'corporate', 'Taj Palace, New Delhi', '2024-12-25 19:30:00', 2, 20000, 30000, ARRAY['Interactive performance', 'Diverse repertoire', 'Professional setup'], 'open', now() - interval '3 days'),
(gen_random_uuid(), (SELECT id FROM profiles LIMIT 1), 'Music Video Shoot', 'Looking for musicians and dancers for an upcoming music video. Great exposure opportunity!', 'video', 'Film City, Mumbai', '2025-01-01 09:00:00', 12, 10000, 20000, ARRAY['Camera comfortable', 'Own costumes', 'Availability for retakes'], 'open', now() - interval '10 days');

-- Sample collaborations
INSERT INTO public.collaborations (id, creator_id, title, description, collaboration_type, location, deadline, max_participants, status, created_at) VALUES
(gen_random_uuid(), (SELECT id FROM profiles LIMIT 1), 'Indo-Fusion Album Project', 'Creating an album that blends Indian classical with contemporary genres. Looking for instrumentalists and producers.', 'album', 'Mumbai, Maharashtra', '2025-06-30 23:59:59', 5, 'open', now() - interval '12 days'),
(gen_random_uuid(), (SELECT id FROM profiles LIMIT 1), 'Monthly Jam Sessions', 'Regular jam sessions for musicians to collaborate and network. All levels welcome!', 'jam_session', 'Bangalore, Karnataka', NULL, 10, 'open', now() - interval '8 days'),
(gen_random_uuid(), (SELECT id FROM profiles LIMIT 1), 'Podcast Music Series', 'Creating background music for a popular podcast series. Need composers and sound designers.', 'project', 'Remote', '2025-04-15 23:59:59', 3, 'open', now() - interval '6 days');